### ISSUE TITLE
Still works in 2024?

### ISSUE THREAD

**Issue by kotAPI** [Reneator/github-godot-ci-test#1]
Hello! Been wondering if this still works in 2024, was exploring solutions to automate my steam releases on different platforms!

**Comment by Reneator** [comment]
Hi, sadly this doesnt work currently, because Steam changed their apis to required MFA (Multifactor authentication). 
For this, to run the steam pipeline, you would have to do a lot of hacks etc. to extract the underlying seed from the MFA from which the mfa code would be generated, so the steam action could then upload the project to steam.

I wasnt able to reproduce that and am waiting for a better possibilty (maybe it already exists and i missed it)

From what i understood the official steam-sdk could maybe be automated via command line script (a sequence of specific commands) to at least upload it semi automatically, but maybe not from withing github

**Comment by kotAPI** [comment]
> Hi, sadly this doesnt work currently, because Steam changed their apis to required MFA (Multifactor authentication). For this, to run the steam pipeline, you would have to do a lot of hacks etc. to extract the underlying seed from the MFA from which the mfa code would be generated, so the steam action could then upload the project to steam.
> 
> I wasnt able to reproduce that and am waiting for a better possibilty (maybe it already exists and i missed it)
> 
> From what i understood the official steam-sdk could maybe be automated via command line script (a sequence of specific commands) to at least upload it semi automatically, but maybe not from withing github

Got it, thanks for the info man! super helpful. I noticed the reddit thread was over 2 years old and was wondering if anyone had managed to get this working with GitHub. I'm a bit late to the party, but good work!

thanks again

**Comment by Reneator** [comment]
Thank you for caring! Wish you all the best!
And hit me up if you find a solution, im currently building my godot project via github actions as that is much easier than manual.
And then download the artifacts and then upload them by hand via steam ui on browser.

**Comment by Reneator** [comment]
Ah, and you can see the MFA part in the steam-deploy action repository:

https://github.com/game-ci/steam-deploy

Setup- 3 A Using MFA Files

so its possible, but that requires the aformentioned hacks.
